# Generated by Django 5.2.8 on 2025-12-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='priests/photos/')),
            ],
        ),
    ]
