# Generated by Django 5.2.8 on 2025-12-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='priest/static/images'),
        ),
    ]
