# Generated by Django 5.2.8 on 2025-12-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priest', '0002_alter_priest_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='priests/'),
        ),
    ]
