# Generated by Django 5.2.8 on 2025-12-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='lyrics',
            field=models.TextField(),
        ),
    ]
