# Generated by Django 5.2.8 on 2025-11-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-date'], 'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
    ]
