# Generated by Django 5.2.8 on 2025-12-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={},
        ),
    ]
