# Generated by Django 5.2.8 on 2025-12-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donationinfo_delete_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationinfo',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
