# Generated by Django 5.2.8 on 2025-12-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donationinfo_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationinfo',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
