"""
Django settings for vcpWebsite project - Virgen Dela Candelaria Parish Website

Generated by 'django-admin startproject' using Django 5.2.8.

IMPORTANT CONFIGURATION NOTES:
  - SECRET_KEY: Change in production! Use environment variable.
  - DEBUG: Set to False in production
  - ALLOWED_HOSTS: Add your domain in production
  - Database: Currently SQLite. Use PostgreSQL in production.
  - Static files: Run 'collectstatic' before deploying

For more information on this file, see:
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import dj_database_url
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================================
# SECURITY SETTINGS
# ============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
# TODO: Move to environment variable in production
SECRET_KEY = 'django-insecure-8x#!=!^zofuy)!bza101i$-6eo7)@#65+=)s-n!1b8@x(-h9nd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False # MUST be False in production
ALLOWED_HOSTS = ['*']

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600
        )
    }
# ============================================================================
# INSTALLED APPS - CUSTOM & DJANGO APPS
# ============================================================================
# Order matters for template/static file discovery

INSTALLED_APPS = [
    # Django built-in apps
    'django.contrib.admin',        # Admin panel
    'django.contrib.auth',         # User authentication
    'django.contrib.contenttypes', # Content types framework
    'django.contrib.sessions',     # Session management
    'django.contrib.messages',     # Messaging framework
    'django.contrib.staticfiles',  # Static files management
    
    # Custom project apps
    'core',           # Main website (home, history, location pages)
    'donations',      # Donation pages and management
    'people',         # Email subscriptions management
    'songs',          # Songs/hymns management (TODO: implement)
    'announcements',  # Announcements management
    'groups',         # Groups management
    'priest',         # Priest management
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'vcpWebsite.urls'

# Static Files configuratio

# 3. SECRET KEY (Crucial)
# NEVER hardcode your SECRET_KEY in the file. Read it from environment variables.
SECRET_KEY = os.environ.get('SECRET_KEY', 'default-key-for-local-dev-only')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vcpWebsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'postgres',         # Check this is correct
        'USER': 'postgres',         # Check this is correct
        'PASSWORD': 'Kezkupom123@@@', # Check this is correct
        'HOST': 'localhost',
        'PORT': '5432',
        
        # <<< ADD THIS SECTION TO FIX THE SSL ERROR >>>
        'OPTIONS': {
            'sslmode': 'disable',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
