# Generated by Django 5.2.8 on 2025-12-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_subscription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.AddField(
            model_name='subscription',
            name='password',
            field=models.CharField(default='placeholder_required_change', max_length=128),
        ),
    ]
