# Generated by Django 5.2.8 on 2025-12-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_subscription_options_subscription_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
