# Generated by Django 5.2.8 on 2025-12-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='created_at',
            field=models.DateField(),
        ),
    ]
