# Generated by Django 5.2.8 on 2025-12-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_churchgroups_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchgroups',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='groups/'),
        ),
    ]
